#!/bin/bash

# Starts a Hydrabadger node
# =========================
#
# Optional environment variables:
#
# * HYDRABADGER_LOG_ADDTL:
#
#   Appends additional logging args (debug, trace, filters, etc.).
#
# * HYDRABADGER_RELEASE:
#
#   Builds in debug mode if `HYDRABADGER_RELEASE` == `0` or `false`.
#   Slows down output and makes reading log easier.
#
#

if [[ $HYDRABADGER_LOG ]]
then
    HYDRABADGER_LOG=$HYDRABADGER_LOG
else
    HYDRABADGER_LOG="info"
fi

if [[ $HYDRABADGER_RELEASE ]]
then
    case "$HYDRABADGER_RELEASE" in
        0|false) RELEASE=""; DIRECTORY="debug" ;;
        *) RELEASE="--release"; DIRECTORY="release" ;;
    esac
else
    RELEASE="--release"
    DIRECTORY="release"
fi

cargo build $RELEASE
bash -c "\
HYDRABADGER_LOG=$HYDRABADGER_LOG target/$DIRECTORY/peer_node \
    -b localhost:3002 \
    -r localhost:3000 \
    -r localhost:3001\
    -r localhost:3003\
    -r localhost:3004\
"

peer_node --bind-address localhost:3002 --remote-address localhost:3000 --remote-address localhost:3001 --remote-address localhost:3003 --remote-address localhost:3004